# Claude Code Usage Window Starter Pipeline
# Purpose: Starts Claude Code usage window at 7am Eastern to reset at 12pm
# Runs Monday-Friday at 7am EST (12:00 UTC) / 7am EDT (11:00 UTC)

trigger: none # No CI triggers

# Schedule: 7am Eastern, Monday through Friday
# Note: Azure Pipelines uses UTC. Adjust between 11:00 (EDT) and 12:00 (EST) as needed
# Current setting: 12:00 UTC = 7am EST (winter) / 8am EDT (summer)
schedules:
  - cron: "0 12 * * Mon-Fri"
    displayName: 'Daily 7am EST usage window starter'
    branches:
      include:
        - main
    always: true # Run even if no code changes

variables:
  - group: AI # Contains ANTHROPIC_API_KEY (if needed) and other secrets
  - name: nodeVersion
    value: '20.x'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: StartUsageWindow
    displayName: 'Start Claude Code Usage Window'
    jobs:
      - job: TestClaudeCode
        displayName: 'Test Claude Code Connection'
        timeoutInMinutes: 10
        steps:
          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: 'Install Node.js'

          # Install Claude Code CLI
          - script: |
              echo "Installing Claude Code CLI..."
              npm install -g @anthropic-ai/claude-code
              claude --version
            displayName: 'Install Claude Code CLI'

          # Download and configure Claude OAuth credentials
          - task: DownloadSecureFile@1
            name: claudeCredentials
            inputs:
              secureFile: '.credentials.json'
            displayName: 'Download Claude OAuth Credentials'

          - script: |
              echo "Setting up Claude OAuth credentials..."
              mkdir -p ~/.claude
              cp $(claudeCredentials.secureFilePath) ~/.claude/.credentials.json
              chmod 600 ~/.claude/.credentials.json
              echo "Claude credentials configured at ~/.claude/.credentials.json"
            displayName: 'Configure Claude OAuth Credentials'

          # Test Claude Code by asking it to respond with "OK"
          - script: |
              set -e
              echo "Testing Claude Code connection..."

              # Run Claude Code with a simple prompt (using same pattern as quick-fix.yml)
              # - </dev/null prevents waiting for stdin
              # - timeout ensures we don't hang forever
              # - CI env vars disable interactive mode
              timeout 60 claude --output-format stream-json --verbose --dangerously-skip-permissions \
                "Please respond with only the word 'OK' and nothing else." \
                </dev/null 2>&1 | tee $(Agent.TempDirectory)/claude-output.txt || true

              echo "----------------------------------------"
              echo "Claude Code output:"
              cat $(Agent.TempDirectory)/claude-output.txt
              echo "----------------------------------------"

              # Check if response contains "OK"
              if grep -qi "OK" $(Agent.TempDirectory)/claude-output.txt; then
                echo "##[section]✓ Claude Code is working correctly!"
                echo "##[section]Usage window started at $(date)"
                echo "##[section]Window will reset at 12pm EST / 1pm EDT"
                exit 0
              else
                echo "##[error]✗ Claude Code did not respond with 'OK'"
                echo "##[error]See output above for details"
                exit 1
              fi
            displayName: 'Test Claude Code - Expect OK Response'
            env:
              ANTHROPIC_API_KEY: $(ANTHROPIC_API_KEY)
              CI: 'true'
              CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: '1'

          # Summary
          - script: |
              echo "========================================="
              echo "Claude Code Usage Window Started"
              echo "========================================="
              echo "Start time: $(date)"
              echo "Window resets in 5 hours (12pm EST / 1pm EDT)"
              echo "========================================="
            displayName: 'Display Summary'
            condition: succeeded()
