#!/bin/bash
# create-pr.sh
# Creates a pull request on GitHub and adds a comment to the Azure DevOps work item
#
# Usage: ./create-pr.sh <work-item-id> <branch-name> <workflow-type> <github-token> <azure-token>

set -e

# Source shared functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/shared-functions.sh"

WORK_ITEM_ID="$1"
BRANCH_NAME="$2"
WORKFLOW_TYPE="$3"
GITHUB_TOKEN="$4"
AZURE_TOKEN="$5"

if [ -z "$WORK_ITEM_ID" ] || [ -z "$BRANCH_NAME" ] || [ -z "$WORKFLOW_TYPE" ] || [ -z "$GITHUB_TOKEN" ]; then
  echo "Usage: $0 <work-item-id> <branch-name> <workflow-type> <github-token> [azure-token]"
  exit 1
fi

# Initialize defaults
init_github_defaults

echo "Creating pull request on GitHub..."
echo "Branch: $BRANCH_NAME -> $TARGET_BRANCH"
echo "Repository: $GITHUB_OWNER/$GITHUB_REPO"

# Determine PR title and body based on workflow type
case "$WORKFLOW_TYPE" in
  "quick-fix")
    PR_TITLE="🔧 Quick Fix: Work Item #$WORK_ITEM_ID"
    PR_BODY="Automated quick fix generated by AI pipeline.

**Work Item:** #$WORK_ITEM_ID
**Type:** Quick Fix (trivial change)

---

⚠️ **Review Checklist:**
- [ ] Changes are minimal and targeted
- [ ] No unintended side effects
- [ ] Tests pass (if applicable)"
    ;;
  "implement")
    PR_TITLE="✨ Implementation: Work Item #$WORK_ITEM_ID"
    PR_BODY="Implementation generated from approved plan by AI pipeline.

**Work Item:** #$WORK_ITEM_ID
**Type:** Planned Implementation

---

⚠️ **Review Checklist:**
- [ ] Implementation matches the approved plan
- [ ] Code follows project conventions
- [ ] Tests included/updated
- [ ] No unintended changes"
    ;;
  *)
    PR_TITLE="🤖 AI Generated: Work Item #$WORK_ITEM_ID"
    PR_BODY="Changes generated by AI pipeline.

**Work Item:** #$WORK_ITEM_ID"
    ;;
esac

# Create PR using GitHub API with HTTP status capture
HTTP_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  -d "$(jq -n \
    --arg title "$PR_TITLE" \
    --arg body "$PR_BODY" \
    --arg head "$BRANCH_NAME" \
    --arg base "$TARGET_BRANCH" \
    '{title: $title, body: $body, head: $head, base: $base}')" \
  "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls")

# Extract HTTP status code (last line) and response body
HTTP_STATUS=$(echo "$HTTP_RESPONSE" | tail -n1)
PR_RESPONSE=$(echo "$HTTP_RESPONSE" | sed '$d')

# Check HTTP status first
if [ "$HTTP_STATUS" -eq 201 ]; then
  # PR created successfully
  PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
  PR_URL=$(echo "$PR_RESPONSE" | jq -r '.html_url')
  echo "Pull Request created successfully!"

elif [ "$HTTP_STATUS" -eq 422 ]; then
  # Check if PR already exists (this is fine - we force-pushed so it has new commits)
  if echo "$PR_RESPONSE" | jq -r '.errors[]?.message' 2>/dev/null | grep -q "pull request already exists"; then
    echo "PR already exists for this branch - finding existing PR..."

    # Get existing PR for this branch
    EXISTING_PR=$(curl -s \
      -H "Authorization: token $GITHUB_TOKEN" \
      -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/pulls?head=$GITHUB_OWNER:$BRANCH_NAME&state=open")

    PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.[0].number')
    PR_URL=$(echo "$EXISTING_PR" | jq -r '.[0].html_url')

    if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" == "null" ]; then
      echo "Error: Could not find existing PR"
      echo "$EXISTING_PR" | jq .
      exit 1
    fi

    echo "Found existing PR #$PR_NUMBER - branch was updated with new commits"
  else
    echo "Error: GitHub API returned HTTP 422"
    echo "Validation failed. This often means:"
    echo "  - The branch doesn't exist on remote"
    echo "  - The base branch '$TARGET_BRANCH' doesn't exist"
    echo ""
    echo "GitHub API response:"
    echo "$PR_RESPONSE" | jq . 2>/dev/null || echo "$PR_RESPONSE"
    exit 1
  fi

else
  echo "Error: GitHub API returned HTTP $HTTP_STATUS"

  case "$HTTP_STATUS" in
    401)
      echo "Authentication failed. Check that GITHUB_PAT is valid and not expired."
      ;;
    403)
      echo "Permission denied. Check that GITHUB_PAT has 'Pull requests: Read and write' permission."
      echo "Token also needs 'Contents: Read and write' to push branches."
      ;;
    404)
      echo "Repository not found or branch doesn't exist."
      echo "Verify repository: $GITHUB_OWNER/$GITHUB_REPO"
      echo "Verify branch '$BRANCH_NAME' was pushed successfully."
      ;;
    *)
      echo "Unexpected error occurred."
      ;;
  esac

  echo ""
  echo "GitHub API response:"
  echo "$PR_RESPONSE" | jq . 2>/dev/null || echo "$PR_RESPONSE"
  exit 1
fi

if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" == "null" ]; then
  echo "Error: PR operation completed but response parsing failed"
  echo "$PR_RESPONSE" | jq .
  exit 1
fi

echo "----------------------------------------"
echo "PR #$PR_NUMBER"
echo "URL: $PR_URL"
echo "----------------------------------------"

# Add comment to Azure DevOps work item (if azure token provided)
if [ -n "$AZURE_TOKEN" ]; then
  echo "Adding comment to Azure DevOps work item..."

  COMMENT_TEXT="PULL REQUEST CREATED ON GITHUB

AI pipeline has created a pull request for this work item.

PR: #$PR_NUMBER
URL: $PR_URL
Branch: $BRANCH_NAME
Type: $WORKFLOW_TYPE

Next Steps:
1. Review the pull request on GitHub
2. Approve and merge when ready"

  # Use the reusable comment script (non-fatal if it fails)
  "$SCRIPT_DIR/add-work-item-comment.sh" "$WORK_ITEM_ID" "$COMMENT_TEXT" "$AZURE_TOKEN" || \
    echo "Warning: Failed to add comment to work item (non-fatal - PR was created successfully)"
fi

# Output PR number for pipeline use
echo "##vso[task.setvariable variable=PR_NUMBER]$PR_NUMBER"
echo "##vso[task.setvariable variable=PR_URL]$PR_URL"
